name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: ros:jazzy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.6
      - name: Install Python dependencies
        run: |
          apt-get update -qq
          apt-get install -y python3-pip
          python3 -m pip install --break-system-packages --ignore-installed -r requirements.txt
          python3 -m pip install --break-system-packages --ignore-installed "setuptools==68.1.2"
          python3 -m pip install --break-system-packages "pytest-cov<6.0" colcon-coveragepy-result
      - name: Build and test
        uses: ros-tooling/action-ros-ci@0.4.8
        with:
          package-name: mqtt_ros
          target-ros2-distro: jazzy
          vcs-repo-file-url: ${{ github.workspace }}/.github/workflows/dependencies.repos
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }
          skip-tests: false
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ros_ws/coveragepy/.coverage
          flags: unittests
          name: codecov-umbrella
          slug: grupo-avispa/mqtt_ros
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
